# Generated by Django 3.1.6 on 2021-02-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('srp_id', models.TextField(blank=True, db_column='SRP_ID', null=True)),
                ('srr_id', models.TextField(blank=True, db_column='SRR_ID', null=True)),
                ('assay_type', models.TextField(blank=True, db_column='Assay_Type', null=True)),
                ('cultivar', models.TextField(blank=True, db_column='Cultivar', null=True)),
                ('treatment', models.TextField(blank=True, db_column='Treatment', null=True)),
                ('stage', models.TextField(blank=True, db_column='Stage', null=True)),
                ('tissue', models.TextField(blank=True, db_column='Tissue', null=True)),
                ('layout', models.TextField(blank=True, db_column='Layout', null=True)),
                ('treat', models.TextField(blank=True, db_column='Treat', null=True)),
            ],
            options={
                'db_table': 'description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tpm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.TextField(blank=True, null=True)),
                ('tpm', models.TextField(blank=True, db_column='Tpm', null=True)),
            ],
            options={
                'db_table': 'tpm',
                'managed': False,
            },
        ),
    ]
